### ISSUE TITLE
Pushing artifacts to PyPI causes Travis CI build to fail

### ISSUE THREAD

**Issue by maurizi** [azavea/django-queryset-csv#101]
When pushing tags, Travis CI automatically pushes a new release of the library to PyPI.
This is working correctly, but we are trying to push artifacts for every combination in our build matrix, which causes all builds in the matrix after the first to fail, since the release is already on PyPI.

We should restrict our `deploy` step to only run once, if possible. Travis CI build stages might be helpful here: https://docs.travis-ci.com/user/build-stages

This isn't actively harmful, since pushing artifacts to PyPI is the last step in the Travis CI test script, and we will separately test the `master` branch at the same time, but it would be nice to fix this.

**Comment by maurizi** [comment]
@azavea/operations This may also be an issue for other Azavea Python libraries that are published to PyPI, I believe we've been using a similar Travis CI configuration on other libraries.

**Comment by hectcastro** [comment]
This has been resolved in other libraries with the `python` or `condition` attribute of `on` under `deploy`:

```yaml
deploy:
  provider: pypi
  user: azavea
  password:
    secure: ...
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "3.6"
    repo: azavea/...
```

If other environment variables are needed, then:

```yaml
deploy:
  provider: pypi
  user: azavea
  password:
    secure: ...
  distributions: sdist bdist_wheel
  on:
    tags: true
    python: "3.6"
    condition: "$TEST = ..."
    repo: azavea/...
```
